version: '3'

services: 
  laravel:
    build:
      context: .
      dockerfile: Laravel.multistage.Dockerfile
    image: mfdg/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    build:
      context: .
      dockerfile: Nginx.ReverseProxy.Dockerfile
    image: mfdg/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
    
networks: 
  laranet:
    driver: bridge