version: '3'

services: 
  laravel:
    build:
      context: .
      dockerfile: Laravel.multistage.Dockerfile
    image: mfdg/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    build:
      context: .
      dockerfile: Nginx.ReverseProxy.Dockerfile
    image: mfdg/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
    depends_on: 
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - laranet
    
networks: 
  laranet:
    driver: bridge